// Golden dataset regression harness.
// Scans test/golden/ for .json files, each containing a canonical entity
// (cached AniList franchise graph), a query, and a list of synthetic releases
// with expected correct/rejected markers. Runs the full normalize →
// tagBranch → validate pipeline against every release and asserts the
// expected outcome.
//
// Run: npm run test:golden
// Golden files are generated by: npm run build:golden

import { readFile, readdir } from 'node:fs/promises'
import { join, extname, basename } from 'node:path'
import { normalizeTorrent, tagBranch } from '../src/lib/normalize.js'
import { validate, pickRequestedBranch } from '../src/lib/filters.js'

const DIR = new URL('./golden/', import.meta.url).pathname.replace(/^\//, '').replace(/%3A/gi, ':')
const entries = await readdir(DIR)
const files = entries.filter(f => extname(f) === '.json')

let totalReleases = 0, passedReleases = 0
let totalGates = 0, passedGates = 0
const failures = []

for (const f of files.sort()) {
  const raw = JSON.parse(await readFile(join(DIR, f), 'utf8'))
  const { name, query, canonical, releases = [] } = raw

  // Restore Set from JSON array (tokens serialized as arrays by the builder).
  for (const b of canonical?.branches || []) {
    b.tokens = new Set(b.tokens || [])
  }

  const requested = pickRequestedBranch(canonical, query.season, null)
  const env = { canonical, requestSeason: query.season, requestFormat: null, requestEpisode: query.episode, mode: 'single' }

  for (const rel of releases) {
    totalReleases++
    const norm = normalizeTorrent({ title: rel.title, tracker: 'golden', seeders: 10, date: '2024-01-01' })
    const tag = tagBranch(norm, canonical)
    const verdict = validate(norm, env)
    const rejected = !verdict.ok

    // Gate 1: tagBranch identifies the correct branch
    const taggedRight = !!tag.branch && !!requested && tag.branch.anilist === requested.anilist
    if (rel.expectCorrect) {
      totalGates++; if (taggedRight) passedGates++; else failures.push({ file: basename(f, '.json'), kind: 'tagBranch-wrong', release: rel.title, got: tag.branch?.anilist, want: requested.anilist })
    } else {
      totalGates++; if (!taggedRight) passedGates++; else failures.push({ file: basename(f, '.json'), kind: 'tagBranch-wrong-adv', release: rel.title, got: tag.branch?.anilist, shouldNotBe: requested.anilist })
    }

    // Gate 2: validate rejects adversarial, accepts correct
    if (rel.expectCorrect) {
      totalGates++; if (!rejected) passedGates++; else failures.push({ file: basename(f, '.json'), kind: 'validate-rejected', release: rel.title, reasons: verdict.reasons })
    } else {
      totalGates++; if (rejected) passedGates++; else failures.push({ file: basename(f, '.json'), kind: 'validate-should-reject', release: rel.title })
    }

    if (rel.expectCorrect ? (!rejected && taggedRight) : (rejected && !taggedRight)) passedReleases++
  }
}

const passRate = totalGates > 0 ? (100 * passedGates / totalGates).toFixed(2) : '0.00'
const relRate = totalReleases > 0 ? (100 * passedReleases / totalReleases).toFixed(1) : '0.0'

console.log('================ GOLDEN DATASET ================')
console.log('golden files:            ', files.length)
console.log('releases:                ', totalReleases)
console.log('releases fully passing:   ', passedReleases + '/' + totalReleases, '(' + relRate + '%)')
console.log('gate assertions passed:   ', passedGates + '/' + totalGates, '(' + passRate + '%)')

if (failures.length) {
  console.log('\nfailures (' + failures.length + '):')
  failures.slice(0, 20).forEach(f => console.log('  ' + f.kind + ' :: ' + (f.release || '').slice(0, 80)))
}

let failed = false
if (passedGates < totalGates) { console.log('\nFAIL: ' + passedGates + '/' + totalGates + ' gate assertions passed'); failed = true }
if (passedReleases < totalReleases) { console.log('\nFAIL: ' + passedReleases + '/' + totalReleases + ' releases fully pass'); failed = true }

console.log('\n' + (failed ? 'FAILED' : 'PASSED'))
process.exit(failed ? 1 : 0)